consensus_web/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, BooleanField, SubmitField, PasswordField, TextAreaField, \
    SelectField, FieldList
from wtforms.validators import DataRequired, Email

from consensus_web.models import OpcaoVoto


class SugerirItemPautaForm(Form):
    titulo = StringField(u'Título: ', validators=[DataRequired("campo obrigatório")])
    descricao = TextAreaField(u'Descrição: ', validators=[DataRequired("campo obrigatório")])
#    assembleia = SelectField(u'Assembléia: ', coerce=int)
    autor = StringField('Autor: ')
#    anexos = FileField('Anexo: ')
    votacao = SelectField(u'Opções de Voto: ', coerce=int)
    outra_opcao_voto = FieldList(StringField(u' '), min_entries=2)

    def __init__(self, *args, **kwargs):
        super(SugerirItemPautaForm, self).__init__(*args, **kwargs)
        opcoes_votacao = OpcaoVoto.query.all()
        self.votacao.choices = [(o.num,o.nome) for o in opcoes_votacao]

    def add_opcao_voto(self):
        self.outra_opcao_voto.append_entry(StringField(u' '))

    def validate(self):
        if not Form.validate(self):
            return False
        result = True

        if self.votacao.data == 3:
            for e in self.outra_opcao_voto.entries:
                if not e.data:
                    self.outra_opcao_voto.errors.append('campo obrigatorio')
                    result = False
        return result


class ReprovarSugestaoForm(Form):
    justificativa = TextAreaField(u'Justificativa: ', validators=[DataRequired("campo obrigatório")])

    def __init__(self, *args, **kwargs):
        super(ReprovarSugestaoForm, self).__init__(*args, **kwargs)


# class CriarAssembleiaForm(Form):
#     data_inicio = DateTimeField(u'Data de Início: ',
#                                 validators=[DataRequired("Data de Início obrigatória")],
#                                 format="%Y-%m-%dT%H:%M") # passar o formato retornado pelo input html5
#
#     data_fim = DateTimeField(u'Data de Término: ',
#                                 validators=[DataRequired("Data de Término obrigatória")],
#                                 format="%Y-%m-%dT%H:%M")
#
#     salvar = SubmitField(u'Criar Assembléia', render_kw={"class": "btn btn-default"})
#
#     def __init__(self, *args, **kwargs):
#         super(CriarAssembleiaForm, self).__init__(*args, **kwargs)

consensus_web/__init__.py
#!/usr/bin/python
from flask import Flask
from flask_login import LoginManager
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CsrfProtect

from config import config_map

db = SQLAlchemy()
login_manager = LoginManager()
## keep track of the client’s IP address and browser agent and will log the user out if it detects a change
login_manager.session_protection = 'strong'
## sets the endpoint for the login page
login_manager.login_view = 'auth.login'
moment = Moment()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_map[config_name])
    config_map[config_name].init_app(app)
    csrf = CsrfProtect(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

# inicializa Flask extensions
    db.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)
    csrf.init_app(app)
# retorna app configurada
    return app

consensus_web/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

# importado no final do arquivo para evitar dependencias ciclicas
from . import views, file_upload_views, errors

# @main.app_context_processor
# def inject_permissions():
#     return dict(Permission=Permission)

consensus_web/main/views.py
## encoding: utf-8

from datetime import datetime

from flask import request, render_template, url_for, redirect, flash, jsonify, json
from flask_login import login_required, current_user

from . import main
from .utils import incluir_anexos, incluir_opcao_voto, get_op_voto_por_sugestao,\
    remover_itens_ja_votados, nenhum_itempauta_ou_listar_com_op_voto,get_op_voto_por_itempauta,gravatar
from .. import db
from ..decorators import permission_required
from ..main.forms import SugerirItemPautaForm, ReprovarSugestaoForm
from ..models import ItemPauta, ConsensusTask, Assembleia, OpcaoVoto, Voto, StatusItemPauta, \
    SugestaoItemPauta, ComentariosItemPauta, Morador


@main.route('/', methods = ['GET','POST'])
@login_required
def index():
    return render_template("index.html",is_home=True)


############################################
############## ITEM DE PAUTA ###############
############################################

@main.route('/listar-itenspauta/<status>', methods = ['GET'])
@login_required
@permission_required(ConsensusTask.LISTAR_ITEM_PAUTA)
def listar_itens_de_pauta_status(status):
    if status not in StatusItemPauta.__members__:
        flash(u"Status inexistente: " + status)
        return redirect(url_for('main.index'))
    # nao mostra sugestoes. Para isso, utilizar o metodo "listar_itenspautas_sugeridos"
    itens_pauta = ItemPauta.query \
        .filter(ItemPauta.status == status).all()
    return nenhum_itempauta_ou_listar_com_op_voto\
        (msg=u"Não há Itens de Pauta com situação " + status, itens_pauta=itens_pauta)


@main.route('/listar-itenspauta/<num_assembleia>/', methods = ['GET'])
@login_required
@permission_required(ConsensusTask.LISTAR_ITEM_PAUTA)
def listar_itens_de_pauta_da_assembleia(num_assembleia):
    itens_pauta = ItemPauta.query\
        .filter(ItemPauta.assembleia == num_assembleia).all()

    return nenhum_itempauta_ou_listar_com_op_voto\
         (msg=u"Não há Itens de Pauta para a Assembléia selecionada", itens_pauta=itens_pauta,
            num_assembleia=num_assembleia)


@main.route('/votar-item-pauta/', methods = ['GET','POST'])
@login_required
@permission_required(ConsensusTask.VOTAR_ITEM_PAUTA)
def votar_itempauta():
    if request.method == 'GET':
        itens_pauta_sugeridos = ItemPauta.query.filter(ItemPauta.status == 'EM_VOTACAO').all()
        if not itens_pauta_sugeridos:
            flash(u"Não há Itens de Pauta EM VOTAÇÃO")
            return redirect(url_for('main.index'))

        itens_pauta_nao_votados_pelo_usuario = remover_itens_ja_votados(itens_pauta_sugeridos, current_user)

        return nenhum_itempauta_ou_listar_com_op_voto\
            (msg=u"Não há Itens de Pauta PENDENTES de voto por você", itens_pauta=itens_pauta_nao_votados_pelo_usuario,
             template="itempauta/listar_itenspauta.html", is_votacao = True)
    else:
        if not request.form.get('link_op_voto'):
            return redirect(url_for('main.votar_itempauta'))

        voto_e_num_itempauta = request.form['link_op_voto']
        voto_e_num_item_split = voto_e_num_itempauta.split(";")
        nome_voto = voto_e_num_item_split[0]
        num_itempauta = voto_e_num_item_split[1]
        autor = current_user.id
        it = ItemPauta.query.get(num_itempauta)
        voto = Voto(autor_email=autor, itempauta_num = it.num, op_nome=nome_voto)

        if 'comentario' in request.form:
            comentario = request.form["comentario"]
            gravatar_src = gravatar(request, current_user.id or "aditil@gmail.com", size=40)
            morador = Morador.query.filter(Morador.usuario_id == autor).one() # somente morador pode comentar
            c = ComentariosItemPauta(texto=comentario,it=it.num,autor=morador.num,gravatar_src=gravatar_src)
            db.session.add(c)
        db.session.add(voto)
        db.session.commit()
        flash("Item de Pauta votado com sucesso")
        return redirect(url_for('main.index'))


@main.route('/detalhar-itenspauta/<num_it>/', methods = ['GET'])
@login_required
@permission_required(ConsensusTask.LISTAR_ITEM_PAUTA)
def detalhar_itempauta(num_it):
    itempauta = ItemPauta.query.get(num_it)
    opcoes_voto = get_op_voto_por_itempauta([itempauta])
    comentarios = ComentariosItemPauta.query.filter(ComentariosItemPauta.itempauta == itempauta.num).all()
    agora = datetime.now();
    return render_template("itempauta/detalhar_itempauta.html", it = itempauta, opcoes_voto = opcoes_voto,
                           comentarios = comentarios, agora = agora)

############################################
######## SUGESTÕES DE ITEM PAUTA ###########
############################################

## tem q permitir GET por causa do possivel refresh do usuario (post/redirect/get pattern)
@main.route('/sugerir-item-pauta/', methods = ['GET','POST'])
@login_required
@permission_required(ConsensusTask.SUGERIR_ITEM_PAUTA)
def sugerir_itempauta():
    form = SugerirItemPautaForm(request.form)
    form.autor.data = current_user.id
    display_div_erro = "display:none"
    if form.validate_on_submit():
        op = OpcaoVoto.query.get(form.votacao.data)
        sugestao = SugestaoItemPauta(titulo=form.titulo.data, autor=form.autor.data, desc=form.descricao.data)
        # se usuario selecionou 'outros' no combo 'opcoes de voto'
        if op.nome.__contains__("outras"):
            nova_op = incluir_opcao_voto(form.outra_opcao_voto.entries, db)
            sugestao.op_voto = nova_op.num
        else:
            sugestao.op_voto = op.num
        db.session.add(sugestao)
        db.session.commit()

        incluir_anexos(db, sugestao.num)

        flash(u"Sugestão de Item de Pauta incluída com sucesso")
        return redirect(url_for('main.index'))
    elif form.errors:
        display_div_erro = "display:inherit"
    return render_template("sugestao/sugerir_itempauta.html", form = form, display=display_div_erro)

# para validar as outras opcoes de voto no wtform
@main.route('/add-opcao-voto/', methods = ['POST'])
@login_required
@permission_required(ConsensusTask.SUGERIR_ITEM_PAUTA)
def add_opcao_voto():
    form = SugerirItemPautaForm(request.form)
    form.add_opcao_voto();
    return json.dumps({'success': True}), 200, {'ContentType': 'application/json'}


@main.route('/listar-sugestoes-sem-avaliacao/', methods = ['GET','POST'])
@login_required
@permission_required(ConsensusTask.AVALIAR_SUGESTAO_ITEM_PAUTA)
def listar_sugestoes_sem_avaliacao():
    form = ReprovarSugestaoForm(request.form)
    return listar_sugestoes_nao_avaliadas(form=form)


def listar_sugestoes_nao_avaliadas(form):
    sugestoes = SugestaoItemPauta.query.filter(SugestaoItemPauta.status == 'NAO_AVALIADA').all()
    if not sugestoes:
        flash(u"Não há Sugestões de Item Pauta A AVALIAR")
        return redirect(url_for('main.index'))
    opcoes_voto = get_op_voto_por_sugestao(sugestoes)
    ids = [(it.num) for it in sugestoes]  # variavel utilizada na pag. "botoes_aprovar_reprovar.html"
    return render_template("sugestao/listar_sugestoes_itempauta.html",
                           itens_de_pauta=zip(sugestoes, ids), opcoes_voto=opcoes_voto, form = form)


@main.route('/listar-sugestoes-reprovadas/', methods = ['GET'])
@login_required
@permission_required(ConsensusTask.LISTAR_ITEM_PAUTA)
def listar_sugestoes_reprovadas():
    sugestoes_reprovadas = SugestaoItemPauta.query.filter(SugestaoItemPauta.status == 'REPROVADA').all()
    return nenhum_itempauta_ou_listar_com_op_voto\
        (msg=u"Não há Sugestões de Item Pauta REPROVADAS", itens_pauta=sugestoes_reprovadas,
               template="sugestao/listar_sugestoes_reprovadas.html")


@main.route('/aprovar-sugestao/<num_sugestao>/', methods = ['POST'])
@login_required
@permission_required(ConsensusTask.AVALIAR_SUGESTAO_ITEM_PAUTA)
def aprovar_sugestao(num_sugestao):
    sugestao = SugestaoItemPauta.query.get(num_sugestao)
    sugestao.status = 'APROVADA'
    flash(u"Sugestão de Item de Pauta APROVADA com sucesso")
    db.session.add(sugestao)
    db.session.commit()
    return "/"  # retorna a url em texto pq o sistema redireciona via javascript apos o confirm do modal


@main.route('/reprovar-sugestao/<num_itempauta>', methods = ['POST'])
@login_required
@permission_required(ConsensusTask.AVALIAR_SUGESTAO_ITEM_PAUTA)
def reprovar_sugestao(num_itempauta):
    form = ReprovarSugestaoForm(request.form)
    if form.validate_on_submit():
        justificativa = request.form["justificativa"]
        sugestao = SugestaoItemPauta.query.get(num_itempauta)
        sugestao.status = 'REPROVADA'
        sugestao.justif_reprovacao = justificativa
        db.session.add(sugestao)
        db.session.commit()
        flash(u"Sugestão de Item Pauta REPROVADA com sucesso")
        return redirect(url_for('main.index'))
    return listar_sugestoes_sem_avaliacao(form=form)


@main.route('/add-itempauta-a-assembleia/', methods = ['POST'])
@login_required
@permission_required(ConsensusTask.ATRIBUIR_ASSEMBLEIA)
def add_itempauta_a_assembleia():
    try:
        num_sugestao = request.form["sugestao_num"]
        if num_sugestao:
            sugestao = SugestaoItemPauta.query.get(num_sugestao)
            return jsonify(num=sugestao.num,titulo=sugestao.titulo,autor=sugestao.autor)
    except Exception as e:
        flash(u'Erro na Aplicação. Contate o Administrador do Sistema')
        return redirect(url_for('main.index'))


@main.route('/atribuir-a-assembleia/', methods = ['GET','POST'])
@login_required
@permission_required(ConsensusTask.ATRIBUIR_ASSEMBLEIA)
def atribuir_sugestoes_a_assembleia():
    if request.method == 'GET':
        assembleias = Assembleia.query.filter_by(status='CRIADA').order_by("num").all()
        sugestoes_aprovadas = SugestaoItemPauta.query.filter(SugestaoItemPauta.status == 'APROVADA').all()

        if not sugestoes_aprovadas:
            flash(u"Não há Sugestões de Item Pauta APROVADAS para atribuir à assembléias")
            return redirect(url_for('main.index'))

consensus_web/templates/macros/exibir_assembleias_e_sugestoes.html
{% macro exibir_assembleias_e_sugestoes(assembleia, opcoes_voto) %}

{% from 'macros/exibir_sugestao_thumbnail.html' import list_sugestao %}

<div class="panel panel-default">
    <div class="panel-heading">
<!--  panel fica sempre aberto p/ não esconder as sugestões adicionadas
      <div class="container" data-toggle="collapse" data-target="#div-sugestoes{{ id }}"> -->
            <h3 class="panel-title form-center" align="center">
                <strong><u> Assembléia {{ assembleia.num }} </u> - </strong>
                inicia em <span class="label label-danger"> {{ assembleia.dataHoraInicio }}</span>
                termina em <span class="label label-warning"> {{ assembleia.dataHoraFim }} </span>
            </h3>
    </div>

    <div class="panel-body">
        <div id="div-sugestoes{{ assembleia.num }}" class="collapse in">
            <div class="row">
            {% for sug in assembleia.sugestoesDosItensPauta %}
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                  <div class="caption">
                      {{ list_sugestao(sug, opcoes_voto) }}
                  </div>

                </div>
              </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endmacro %}

consensus_web/templates/macros/exibir_itempauta_thumbnail.html
{% macro list_itempauta(it, opcoes_voto) %}

    <form action="{{ url_for('main.votar_itempauta') }}" method="POST">

    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {% if it.get_obj_sugestao.titulo %}
         <p>
           <h3>{{ it.get_obj_sugestao.titulo }}</h3>
         </p>
    {% endif %}

    {% if opcoes_voto and current_user.is_morador == "Sim"%}
        <hr>
        <p>
            <div class="btn-group" data-toggle="buttons" role="group">
              {% for op in opcoes_voto.get(it.num) %}
                  <label class="btn btn-default">
                    <input type="radio" name="link_op_voto" id="link_op_voto{{it.num}}"
                           autocomplete="off" value="{{op}} ; {{it.num}}" required>
                     <strong>{{ op }}</strong>
                  </label>
               {% endfor %}
            </div>

        </p>
    {% endif %}

    <hr>

    {% if current_user.is_morador=="Sim" %}
    <p>
        <h4 align="center"><strong>Seu Comentário</strong></h4>
        <textarea name="comentario" id="comentario" class="form-control" style="height: 60px !important;"></textarea>
    </p>
    {% endif %}

    <p>
        <a href="{{ url_for('main.detalhar_itempauta',num_it=it.num) }}"> ver mais </a>
    </p>

    {% if is_votacao %}
    <div class="center-block text-center">
        <input type="submit" class="btn btn-primary" id="votar" value="Confirmar">
    </div>
    {% endif %}

    </form>

{% endmacro %}

consensus_web/templates/macros/exibir_sugestao_thumbnail.html
{% macro list_sugestao(it, opcoes_voto) %}

    {% if it.titulo %}
     <p>
       <h3>{{ it.titulo }}</h3>
     </p>
    {% endif %}

    {% if it.descricao %}
    <hr>
    <longdesc>{{ it.descricao }}</longdesc>
    <hr>
    {% endif %}

    {% if it.autor %}
    <p>
        {{ it.nomeAutor }}
    </p>
    {% else %}
    <p>
        <font color="red"><b> [usuario removido] </b></font>
    </p>
    {% endif %}

    {% if opcoes_voto %}
    <p>
      {% for op in opcoes_voto.get(it.num) %}
        <strong>{{ op }} | </strong>
      {% endfor %}
    </p>
    {% endif %}

    {% for a in it.anexos %}
    <p>
        <a href="{{ a.url_download }}">{{a.nome}}</a>
    </p>
    {% endfor %}

{% endmacro %}