consensus_web/main/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, BooleanField, SubmitField, PasswordField, TextAreaField, \
    SelectField, FieldList
from wtforms.validators import DataRequired, Email

from consensus_web.models import OpcaoVoto


class SugerirItemPautaForm(Form):
    titulo = StringField(u'Título: ', validators=[DataRequired("campo obrigatório")])
    descricao = TextAreaField(u'Descrição: ', validators=[DataRequired("campo obrigatório")])
#    assembleia = SelectField(u'Assembléia: ', coerce=int)
    autor = StringField('Autor: ')
#    anexos = FileField('Anexo: ')
    votacao = SelectField(u'Opções de Voto: ', coerce=int)
    outra_opcao_voto = FieldList(StringField(u' '), min_entries=2)

    def __init__(self, *args, **kwargs):
        super(SugerirItemPautaForm, self).__init__(*args, **kwargs)
        opcoes_votacao = OpcaoVoto.query.all()
        self.votacao.choices = [(o.num,o.nome) for o in opcoes_votacao]

    def add_opcao_voto(self):
        self.outra_opcao_voto.append_entry(StringField(u' '))

    def validate(self):
        if not Form.validate(self):
            return False
        result = True

        if self.votacao.data == 3:
            for e in self.outra_opcao_voto.entries:
                if not e.data:
                    self.outra_opcao_voto.errors.append('campo obrigatorio')
                    result = False
        return result


class ReprovarSugestaoForm(Form):
    justificativa = TextAreaField(u'Justificativa: ', validators=[DataRequired("campo obrigatório")])

    def __init__(self, *args, **kwargs):
        super(ReprovarSugestaoForm, self).__init__(*args, **kwargs)


# class CriarAssembleiaForm(Form):
#     data_inicio = DateTimeField(u'Data de Início: ',
#                                 validators=[DataRequired("Data de Início obrigatória")],
#                                 format="%Y-%m-%dT%H:%M") # passar o formato retornado pelo input html5
#
#     data_fim = DateTimeField(u'Data de Término: ',
#                                 validators=[DataRequired("Data de Término obrigatória")],
#                                 format="%Y-%m-%dT%H:%M")
#
#     salvar = SubmitField(u'Criar Assembléia', render_kw={"class": "btn btn-default"})
#
#     def __init__(self, *args, **kwargs):
#         super(CriarAssembleiaForm, self).__init__(*args, **kwargs)

consensus_web/__init__.py
#!/usr/bin/python
from flask import Flask
from flask_login import LoginManager
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CsrfProtect

from config import config_map

db = SQLAlchemy()
login_manager = LoginManager()
## keep track of the client’s IP address and browser agent and will log the user out if it detects a change
login_manager.session_protection = 'strong'
## sets the endpoint for the login page
login_manager.login_view = 'auth.login'
moment = Moment()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_map[config_name])
    config_map[config_name].init_app(app)
    csrf = CsrfProtect(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

# inicializa Flask extensions
    db.init_app(app)
    login_manager.init_app(app)
    moment.init_app(app)
    csrf.init_app(app)
# retorna app configurada
    return app

consensus_web/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

# importado no final do arquivo para evitar dependencias ciclicas
from . import views, file_upload_views, errors

# @main.app_context_processor
# def inject_permissions():
#     return dict(Permission=Permission)

consensus_web/main/views.py
## encoding: utf-8

from datetime import datetime

from flask import request, render_template, url_for, redirect, flash, jsonify, json
from flask_login import login_required, current_user

from . import main
from .utils import incluir_anexos, incluir_opcao_voto, get_op_voto_por_sugestao,\
    remover_itens_ja_votados, nenhum_itempauta_ou_listar_com_op_voto,get_op_voto_por_itempauta,gravatar
from .. import db
from ..decorators import permission_required
from ..main.forms import SugerirItemPautaForm, ReprovarSugestaoForm
from ..models import ItemPauta, ConsensusTask, Assembleia, OpcaoVoto, Voto, StatusItemPauta, \
    SugestaoItemPauta, ComentariosItemPauta, Morador


@main.route('/', methods = ['GET','POST'])
@login_required
def index():
    return render_template("index.html",is_home=True)


############################################
############## ITEM DE PAUTA ###############
############################################

@main.route('/listar-itenspauta/<status>', methods = ['GET'])
@login_required
@permission_required(ConsensusTask.LISTAR_ITEM_PAUTA)
def listar_itens_de_pauta_status(status):
    if status not in StatusItemPauta.__members__:
        flash(u"Status inexistente: " + status)
        return redirect(url_for('main.index'))
    # nao mostra sugestoes. Para isso, utilizar o metodo "listar_itenspautas_sugeridos"
    itens_pauta = ItemPauta.query \
        .filter(ItemPauta.status == status).all()
    return nenhum_itempauta_ou_listar_com_op_voto\
        (msg=u"Não há Itens de Pauta com situação " + status, itens_pauta=itens_pauta)


@main.route('/listar-itenspauta/<num_assembleia>/', methods = ['GET'])
@login_required
@permission_required(ConsensusTask.LISTAR_ITEM_PAUTA)
def listar_itens_de_pauta_da_assembleia(num_assembleia):
    itens_pauta = ItemPauta.query\
        .filter(ItemPauta.assembleia == num_assembleia).all()

    return nenhum_itempauta_ou_listar_com_op_voto\
         (msg=u"Não há Itens de Pauta para a Assembléia selecionada", itens_pauta=itens_pauta,
            num_assembleia=num_assembleia)


@main.route('/votar-item-pauta/', methods = ['GET','POST'])
@login_required
@permission_required(ConsensusTask.VOTAR_ITEM_PAUTA)
def votar_itempauta():
    if request.method == 'GET':
        itens_pauta_sugeridos = ItemPauta.query.filter(ItemPauta.status == 'EM_VOTACAO').all()
        if not itens_pauta_sugeridos:
            flash(u"Não há Itens de Pauta EM VOTAÇÃO")
            return redirect(url_for('main.index'))

        itens_pauta_nao_votados_pelo_usuario = remover_itens_ja_votados(itens_pauta_sugeridos, current_user)

        return nenhum_itempauta_ou_listar_com_op_voto\
            (msg=u"Não há Itens de Pauta PENDENTES de voto por você", itens_pauta=itens_pauta_nao_votados_pelo_usuario,
             template="itempauta/listar_itenspauta.html", is_votacao = True)
    else:
        if not request.form.get('link_op_voto'):
            return redirect(url_for('main.votar_itempauta'))

        voto_e_num_itempauta = request.form['link_op_voto']
        voto_e_num_item_split = voto_e_num_itempauta.split(";")
        nome_voto = voto_e_num_item_split[0]
        num_itempauta = voto_e_num_item_split[1]
        autor = current_user.id
        it = ItemPauta.query.get(num_itempauta)
        voto = Voto(autor_email=autor, itempauta_num = it.num, op_nome=nome_voto)

        if 'comentario' in request.form:
            comentario = request.form["comentario"]
            gravatar_src = gravatar(request, current_user.id or "aditil@gmail.com", size=40)
            morador = Morador.query.filter(Morador.usuario_id == autor).one() # somente morador pode comentar
            c = ComentariosItemPauta(texto=comentario,it=it.num,autor=morador.num,gravatar_src=gravatar_src)
            db.session.add(c)
        db.session.add(voto)
        db.session.commit()
        flash("Item de Pauta votado com sucesso")
        return redirect(url_for('main.index'))


@main.route('/detalhar-itenspauta/<num_it>/', methods = ['GET'])
@login_required
@permission_required(ConsensusTask.LISTAR_ITEM_PAUTA)
def detalhar_itempauta(num_it):
    itempauta = ItemPauta.query.get(num_it)
    opcoes_voto = get_op_voto_por_itempauta([itempauta])
    comentarios = ComentariosItemPauta.query.filter(ComentariosItemPauta.itempauta == itempauta.num).all()
    agora = datetime.now();
    return render_template("itempauta/detalhar_itempauta.html", it = itempauta, opcoes_voto = opcoes_voto,
                           comentarios = comentarios, agora = agora)

############################################
######## SUGESTÕES DE ITEM PAUTA ###########
############################################

## tem q permitir GET por causa do possivel refresh do usuario (post/redirect/get pattern)
@main.route('/sugerir-item-pauta/', methods = ['GET','POST'])
@login_required
@permission_required(ConsensusTask.SUGERIR_ITEM_PAUTA)
def sugerir_itempauta():
    form = SugerirItemPautaForm(request.form)
    form.autor.data = current_user.id
    display_div_erro = "display:none"
    if form.validate_on_submit():
        op = OpcaoVoto.query.get(form.votacao.data)
        sugestao = SugestaoItemPauta(titulo=form.titulo.data, autor=form.autor.data, desc=form.descricao.data)
        # se usuario selecionou 'outros' no combo 'opcoes de voto'
        if op.nome.__contains__("outras"):
            nova_op = incluir_opcao_voto(form.outra_opcao_voto.entries, db)
            sugestao.op_voto = nova_op.num
        else:
            sugestao.op_voto = op.num
        db.session.add(sugestao)
        db.session.commit()

        incluir_anexos(db, sugestao.num)

        flash(u"Sugestão de Item de Pauta incluída com sucesso")
        return redirect(url_for('main.index'))
    elif form.errors:
        display_div_erro = "display:inherit"
    return render_template("sugestao/sugerir_itempauta.html", form = form, display=display_div_erro)

# para validar as outras opcoes de voto no wtform
@main.route('/add-opcao-voto/', methods = ['POST'])
@login_required
@permission_required(ConsensusTask.SUGERIR_ITEM_PAUTA)
def add_opcao_voto():
    form = SugerirItemPautaForm(request.form)
    form.add_opcao_voto();
    return json.dumps({'success': True}), 200, {'ContentType': 'application/json'}


@main.route('/listar-sugestoes-sem-avaliacao/', methods = ['GET','POST'])
@login_required
@permission_required(ConsensusTask.AVALIAR_SUGESTAO_ITEM_PAUTA)
def listar_sugestoes_sem_avaliacao():
    form = ReprovarSugestaoForm(request.form)
    return listar_sugestoes_nao_avaliadas(form=form)


def listar_sugestoes_nao_avaliadas(form):
    sugestoes = SugestaoItemPauta.query.filter(SugestaoItemPauta.status == 'NAO_AVALIADA').all()
    if not sugestoes:
        flash(u"Não há Sugestões de Item Pauta A AVALIAR")
        return redirect(url_for('main.index'))
    opcoes_voto = get_op_voto_por_sugestao(sugestoes)
    ids = [(it.num) for it in sugestoes]  # variavel utilizada na pag. "botoes_aprovar_reprovar.html"
    return render_template("sugestao/listar_sugestoes_itempauta.html",
                           itens_de_pauta=zip(sugestoes, ids), opcoes_voto=opcoes_voto, form = form)


@main.route('/listar-sugestoes-reprovadas/', methods = ['GET'])
@login_required
@permission_required(ConsensusTask.LISTAR_ITEM_PAUTA)
def listar_sugestoes_reprovadas():
    sugestoes_reprovadas = SugestaoItemPauta.query.filter(SugestaoItemPauta.status == 'REPROVADA').all()
    return nenhum_itempauta_ou_listar_com_op_voto\
        (msg=u"Não há Sugestões de Item Pauta REPROVADAS", itens_pauta=sugestoes_reprovadas,
               template="sugestao/listar_sugestoes_reprovadas.html")


@main.route('/aprovar-sugestao/<num_sugestao>/', methods = ['POST'])
@login_required
@permission_required(ConsensusTask.AVALIAR_SUGESTAO_ITEM_PAUTA)
def aprovar_sugestao(num_sugestao):
    sugestao = SugestaoItemPauta.query.get(num_sugestao)
    sugestao.status = 'APROVADA'
    flash(u"Sugestão de Item de Pauta APROVADA com sucesso")
    db.session.add(sugestao)
    db.session.commit()
    return "/"  # retorna a url em texto pq o sistema redireciona via javascript apos o confirm do modal


@main.route('/reprovar-sugestao/<num_itempauta>', methods = ['POST'])
@login_required
@permission_required(ConsensusTask.AVALIAR_SUGESTAO_ITEM_PAUTA)
def reprovar_sugestao(num_itempauta):
    form = ReprovarSugestaoForm(request.form)
    if form.validate_on_submit():
        justificativa = request.form["justificativa"]
        sugestao = SugestaoItemPauta.query.get(num_itempauta)
        sugestao.status = 'REPROVADA'
        sugestao.justif_reprovacao = justificativa
        db.session.add(sugestao)
        db.session.commit()
        flash(u"Sugestão de Item Pauta REPROVADA com sucesso")
        return redirect(url_for('main.index'))
    return listar_sugestoes_sem_avaliacao(form=form)


@main.route('/add-itempauta-a-assembleia/', methods = ['POST'])
@login_required
@permission_required(ConsensusTask.ATRIBUIR_ASSEMBLEIA)
def add_itempauta_a_assembleia():
    try:
        num_sugestao = request.form["sugestao_num"]
        if num_sugestao:
            sugestao = SugestaoItemPauta.query.get(num_sugestao)
            return jsonify(num=sugestao.num,titulo=sugestao.titulo,autor=sugestao.autor)
    except Exception as e:
        flash(u'Erro na Aplicação. Contate o Administrador do Sistema')
        return redirect(url_for('main.index'))


@main.route('/atribuir-a-assembleia/', methods = ['GET','POST'])
@login_required
@permission_required(ConsensusTask.ATRIBUIR_ASSEMBLEIA)
def atribuir_sugestoes_a_assembleia():
    if request.method == 'GET':
        assembleias = Assembleia.query.filter_by(status='CRIADA').order_by("num").all()
        sugestoes_aprovadas = SugestaoItemPauta.query.filter(SugestaoItemPauta.status == 'APROVADA').all()

        if not sugestoes_aprovadas:
            flash(u"Não há Sugestões de Item Pauta APROVADAS para atribuir à assembléias")
            return redirect(url_for('main.index'))

consensus_web/templates/405.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
    <h1>Houve um erro interno no servidor</h1>
    <h1>Contate o administrador do sistema</h1>
</div>
{% endblock %}

consensus_web/templates/botoes_aprovar_reprovar.html
<p>
    <button type="button" name="link_aprovar" class="btn btn-primary" data-id="{{ it.num }}"
        data-target="#modal" data-toggle="modal">
          <strong>Aprovar</strong>
    </button>

    <input type="hidden" value="" id="num_sugestao">

    <a class="btn btn-danger" role="button" data-toggle="collapse" href="#{{ ids }}"
       aria-expanded="false" id="btn_reprovar" aria-controls="{{ ids }}" >
        <strong>Reprovar</strong>
    </a>
</p>
<p>
    <div class="collapse" id="{{ ids }}">
        <form action="{{ url_for('main.reprovar_sugestao',num_itempauta = it.num) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

            {{ form.justificativa(class="form-control",style="height: 60px !important;", required="True") }}

            {% for error in form.justificativa.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}<br>
            <br>
            <input type="submit" class="btn btn-default" id="ok" value="OK">
        </form>
    </div>
</p>

consensus_web/templates/erro.html
<!DOCTYPE html>

<html>
<head>
    <title>Erro no Sistema</title>
</head>
<body>
    <h1>{{msg}}</h1>
</body>
</html>

consensus_web/templates/file_upload.html
<div class="container">
        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <div class="btn btn-success fileinput-button" id="file-upload">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span >Escolher Arquivo</span>
                    <input type="file" style="opacity: 0"  name="files" multiple>
                </div>
                <!-- The global file processing state -->
                <span class="fileupload-process"></span>

                <button type="button" class="btn btn-danger" data-toggle="popover" data-placement="right" data-html="true"
                    data-content="<li>Tamanho máximo do arquivo: <strong>5 MB</strong></li>
                    <li> Extensões permitidas: <strong>TXT, JPG, GIF, PNG, BMP, DOC, DOCX, XLS, XLSX e PDF </strong></li>
                    <li> Você pode arrastar e soltar do seu desktop aqui </li>">
                    Instruções
                </button>


                <br>

            </div>
            <!-- The global progress state -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>

consensus_web/templates/index.html
{% extends "template_base.html" %}

{% block navbar %}

<nav class="navbar navbar-default no-margin">
<!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header fixed-brand">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"  id="menu-toggle">
          <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>
        </button>
        <a class="navbar-brand" href="#">OLIVERSYS</a>
    </div><!-- navbar-header-->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="active">
                <button class="navbar-toggle collapse in"  data-toggle="collapse" id="menu-toggle-2">
                <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span></button>
            </li>
        </ul>
        <h3 align="center">{% block form_title %} {% endblock %}</h3>
        <div align="right"><b>{{ current_user.nome }} {{ current_user.sobrenome }}</b></div>

    </div><!-- bs-example-navbar-collapse-1 -->
</nav>

<div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <div class="sidebar-nav nav-pills nav-stacked" id="menu">

            <li>
                <a href="{{ url_for('main.index') }}">
                    <span class="fa-stack fa-lg pull-left">
                        <i class="fa fa-dashboard fa-stack-1x "></i>
                    </span>
                    Home
                </a>
            </li>

            {% if not current_user.is_administrador %}
            <li>
                <a href="#">
                    <span class="fa-stack fa-lg pull-left">
                        <i class="fa fa-flag fa-stack-1x "></i>
                    </span> Sugestão de Item Pauta
                </a>
                <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                    {% if current_user.role == 2 %}
                    <li>
                        <a href="{{ url_for('main.sugerir_itempauta') }}">
                            Criar
                        </a>
                    </li>
                    {% endif %}

                    {% if current_user.role == 3 %}
                    <li>
                        <a href="{{ url_for('main.listar_sugestoes_sem_avaliacao') }}">
                            Avaliar
                        </a>
                    </li>
                    {% endif %}

                    {% if current_user.role == 3 or current_user.role == 4 %}
                    <li>
                        <a href="{{ url_for('main.listar_sugestoes_reprovadas') }}">
                            Listar Reprovadas
                        </a>
                    </li>
                    {% endif %}

                    {% if current_user.role == 3 %}
                    <li>
                        <a href="{{ url_for('main.atribuir_sugestoes_a_assembleia') }}">
                            Atribuir à Assembléia
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </li>
            {% endif %}

            {% if current_user.role == 2 %}
            <li>
                <a href="#">
                    <span class="fa-stack fa-lg pull-left">
                        <i class="fa fa-flag fa-stack-1x "></i>
                    </span> Item de Pauta
                </a>
                <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                    <li>
                        <a href="{{ url_for('main.votar_itempauta') }}">
                            Votar
                        </a>
                    </li>
                </ul>
            </li>
            {% endif %}

            {% if current_user.role == 3 or current_user.role == 4 %}
            <li>
                <a href="#">
                    <span class="fa-stack fa-lg pull-left">
                        <i class="fa fa-flag fa-stack-1x "></i>
                    </span> Assembléia
                </a>
                <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                    <li>
                        <a href="{{ url_for('main.criar_assembleia') }}">
                            Criar
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.listar_assembleias',status=1) }}">
                            Aguardando Início
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.listar_assembleias',status=2) }}">
                            Em Andamento
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.listar_assembleias',status=3) }}">
                            Encerradas
                        </a>
                    </li>
                </ul>
            </li>
            {% endif %}

            <li class="divider"></li>


            <li>
                <a href="#">
                    <span class="fa-stack fa-lg pull-left">
                        <i class="fa fa-flag fa-stack-1x "></i>
                    </span> Administração do Sistema
                </a>
                <ul class="nav-pills nav-stacked" style="list-style-type:none;">
                    <li>
                        <a href="{{ url_for('auth.exibir_usuarios') }}">
                            Listar Usuários
                        </a>
                    </li>
                    {% if current_user.is_administrador %}
                    <li>
                        <a href="{{ url_for('auth.add_user') }}">
                            Criar Usuário
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </li>


            {% if current_user.is_authenticated %}
            <li>
                <a href="{{ url_for('auth.logout') }}">
                    <span><i class="glyphicon glyphicon-off"></i></span>
                    Sair
                </a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for('auth.login') }}">
                    <span><i class="fa fa-user fa-lg"></i></span>
                     Entrar
                </a>
            </li>
            {% endif %}
        </div>
    </div><!-- /#sidebar-wrapper -->


    <!-- CONTEUDO DA PAGINA -->
    <div id="page-content-wrapper">
        <div class="container-fluid xyz">
            {% block form %}

                {% for message in get_flashed_messages() %}
                <div class="alert alert-success" role="alert"  align="center">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <span class="sr-only"></span>
                    {{ message }}
                </div>
                {% endfor %}

            {% endblock %}
        </div>
        <br>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->
{% endblock %}

consensus_web/templates/login.html
<head>
    <title>Sistema Consensus - Login </title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="./static/js/jquery-1.11.1.min.js"></script>
    <script src="./static/js/bootstrap.min.js"></script>
    <script src="./static/js/jquery.backstretch.min.js"></script>
    <script src="./static/js/login-form.js"></script>

    <link rel="stylesheet" href="./static/css/bootstrap.min.css">
    <link rel="stylesheet" href="./static/fonts/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="./static/css/form-elements.css">
    <link rel="stylesheet" href="./static/css/style.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="./static/ico/favicon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="./static/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="./static/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="./static/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="./static/ico/apple-touch-icon-57-precomposed.png">
</head>

<body>
        <!-- Top content -->
        <div class="top-content">

            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2 text">
                            <p>
                                <h1><strong><font size="14px" color="#ffbb7d">Consensus</font></strong></h1>
                                <h1>Sistema de Assembéia Online</h1>
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3 form-box">
                            <div class="form-top">
                                <div class="form-top-left">
                                    <h3>Login</h3>
                                    <p>Informe seu e-mail e senha para entrar no sistema:</p>
                                </div>
                                <div class="form-top-right">
                                    <i class="fa fa-key"></i>
                                </div>
                            </div>
                            <div class="form-bottom">
                                <form role="form" action="{{ url_for('auth.login') }}" method="post" class="login-form">
                                    {{ form.hidden_tag() }}
                                    <div class="form-group">
                                        {{ form.email(required="True") }}
                                        {% for error in form.email.errors %}
                                            <span style="color: red;">[{{ error }}]</span>
                                        {% endfor %}<br>
                                    </div>
                                    <div class="form-group">
                                        {{ form.password(required="True") }}
                                        {% for error in form.password.errors %}
                                            <span style="color: red;">[{{ error }}]</span>
                                        {% endfor %}<br>
                                    </div>
                                    <div class="form-group">
                                        {{ form.remember_me }}
                                        <span style="color:white;font-weight:100">{{ form.remember_me.label }}</span>
                                    </div>
                                    <div class="form-group">
                                        {{ form.submit }}
                                    </div>
                                </form>
                            </div>
                            <br>
                            {% for message in get_flashed_messages() %}
                            <div class="alert alert-danger" role="alert">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                <span class="sr-only"></span>
                                {{ message }}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
</body>

consensus_web/templates/modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">{{ modal_title }}</h4>
      </div>
      <div class="modal-body">
          <div class="row">
              <div class="col-sm-10">
                {{ modal_msg }}
              </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>

        <button type="button" id="btn_confirmar" class="btn btn-primary">
            Confirmar
        </button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->